
Flag = [  "Alpgen:setHeavyMasses",
  "Alpgen:setLightMasses",
  "Alpgen:setMLM",
  "Alpgen:setNjet",
  "BeamRemnants:allowBeamJunction",
  "BeamRemnants:allowJunction",
  "BeamRemnants:beamJunction",
  "BeamRemnants:primordialKT",
  "BeamRemnants:rescatterRestoreY",
  "Beams:allowMomentumSpread",
  "Beams:allowVertexSpread",
  "Beams:newLHEFsameInit",
  "Beams:readLHEFheaders",
  "Beams:setProductionScalesFromLHEF",
  "Beams:strictLHEFscale",
  "BoseEinstein:Eta",
  "BoseEinstein:Kaon",
  "BoseEinstein:Pion",
  "Bottomonium:all",
  "Charmonium:all",
  "Check:abortIfVeto",
  "Check:event",
  "Check:history",
  "Check:particleData",
  "ColourReconnection:allowDoubleJunRem",
  "ColourReconnection:allowJunctions",
  "ColourReconnection:forceHadronLevelCR",
  "ColourReconnection:forceResonance",
  "ColourReconnection:lowerLambdaOnly",
  "ColourReconnection:reconnect",
  "ColourReconnection:sameNeighbourColours",
  "ColourReconnection:singleReconnection",
  "ContactInteractions:QCffbar2eebar",
  "ContactInteractions:QCffbar2mumubar",
  "ContactInteractions:QCffbar2tautaubar",
  "ContactInteractions:QCqq2qq",
  "ContactInteractions:QCqqbar2qqbar",
  "Diffraction:doHard",
  "ExcitedFermion:all",
  "ExcitedFermion:bg2bStar",
  "ExcitedFermion:cg2cStar",
  "ExcitedFermion:dg2dStar",
  "ExcitedFermion:egm2eStar",
  "ExcitedFermion:mugm2muStar",
  "ExcitedFermion:qq2bStarq",
  "ExcitedFermion:qq2cStarq",
  "ExcitedFermion:qq2dStarq",
  "ExcitedFermion:qq2sStarq",
  "ExcitedFermion:qq2uStarq",
  "ExcitedFermion:qqbar2eStare",
  "ExcitedFermion:qqbar2eStareStar",
  "ExcitedFermion:qqbar2muStarmu",
  "ExcitedFermion:qqbar2muStarmuStar",
  "ExcitedFermion:qqbar2nueStarnue",
  "ExcitedFermion:qqbar2nueStarnueStar",
  "ExcitedFermion:qqbar2numuStarnumu",
  "ExcitedFermion:qqbar2numuStarnumuStar",
  "ExcitedFermion:qqbar2nutauStarnutau",
  "ExcitedFermion:qqbar2nutauStarnutauStar",
  "ExcitedFermion:qqbar2tauStartau",
  "ExcitedFermion:qqbar2tauStartauStar",
  "ExcitedFermion:sg2sStar",
  "ExcitedFermion:taugm2tauStar",
  "ExcitedFermion:ug2uStar",
  "ExtraDimensionsG*:all",
  "ExtraDimensionsG*:ffbar2G*",
  "ExtraDimensionsG*:gg2G*",
  "ExtraDimensionsG*:gg2G*g",
  "ExtraDimensionsG*:qg2G*q",
  "ExtraDimensionsG*:qqbar2G*g",
  "ExtraDimensionsG*:qqbar2KKgluon*",
  "ExtraDimensionsG*:SMinBulk",
  "ExtraDimensionsG*:VLVL",
  "ExtraDimensionsLED:dijets",
  "ExtraDimensionsLED:ffbar2gammagamma",
  "ExtraDimensionsLED:ffbar2Ggamma",
  "ExtraDimensionsLED:ffbar2GZ",
  "ExtraDimensionsLED:ffbar2llbar",
  "ExtraDimensionsLED:gg2DJgg",
  "ExtraDimensionsLED:gg2DJqqbar",
  "ExtraDimensionsLED:gg2gammagamma",
  "ExtraDimensionsLED:gg2Gg",
  "ExtraDimensionsLED:gg2llbar",
  "ExtraDimensionsLED:GravScalar",
  "ExtraDimensionsLED:monojet",
  "ExtraDimensionsLED:qg2DJqg",
  "ExtraDimensionsLED:qg2Gq",
  "ExtraDimensionsLED:qq2DJqq",
  "ExtraDimensionsLED:qqbar2DJgg",
  "ExtraDimensionsLED:qqbar2DJqqbarNew",
  "ExtraDimensionsLED:qqbar2Gg",
  "ExtraDimensionsTEV:ffbar2bbbar",
  "ExtraDimensionsTEV:ffbar2ccbar",
  "ExtraDimensionsTEV:ffbar2ddbar",
  "ExtraDimensionsTEV:ffbar2e+e-",
  "ExtraDimensionsTEV:ffbar2mu+mu-",
  "ExtraDimensionsTEV:ffbar2nuenuebar",
  "ExtraDimensionsTEV:ffbar2numunumubar",
  "ExtraDimensionsTEV:ffbar2nutaunutaubar",
  "ExtraDimensionsTEV:ffbar2ssbar",
  "ExtraDimensionsTEV:ffbar2tau+tau-",
  "ExtraDimensionsTEV:ffbar2ttbar",
  "ExtraDimensionsTEV:ffbar2uubar",
  "ExtraDimensionsUnpart:ffbar2gammagamma",
  "ExtraDimensionsUnpart:ffbar2llbar",
  "ExtraDimensionsUnpart:ffbar2Ugamma",
  "ExtraDimensionsUnpart:ffbar2UZ",
  "ExtraDimensionsUnpart:gg2gammagamma",
  "ExtraDimensionsUnpart:gg2llbar",
  "ExtraDimensionsUnpart:gg2Ug",
  "ExtraDimensionsUnpart:monojet",
  "ExtraDimensionsUnpart:qg2Uq",
  "ExtraDimensionsUnpart:qqbar2Ug",
  "FourthBottom:all",
  "FourthBottom:ffbar2bPrimebPrimebar(s:gmZ)",
  "FourthBottom:ffbar2bPrimeqbar(s:W)",
  "FourthBottom:ffbar2bPrimetbar(s:W)",
  "FourthBottom:gg2bPrimebPrimebar",
  "FourthBottom:qq2bPrimeq(t:W)",
  "FourthBottom:qqbar2bPrimebPrimebar",
  "FourthPair:ffbar2tauPrimenuPrimebar(s:W)",
  "FourthPair:ffbar2tPrimebPrimebar(s:W)",
  "FourthTop:all",
  "FourthTop:ffbar2tPrimeqbar(s:W)",
  "FourthTop:ffbar2tPrimetPrimebar(s:gmZ)",
  "FourthTop:gg2tPrimetPrimebar",
  "FourthTop:qq2tPrimeq(t:W)",
  "FourthTop:qqbar2tPrimetPrimebar",
  "HadronLevel:all",
  "HadronLevel:BoseEinstein",
  "HadronLevel:Decay",
  "HadronLevel:Hadronize",
  "HadronScatter:afterDecay",
  "HadronScatter:allowDecayProd",
  "HadronScatter:scatter",
  "HadronScatter:scatterRepeat",
  "HadronScatter:tile",
  "HardQCD:3parton",
  "HardQCD:all",
  "HardQCD:gg2bbbar",
  "HardQCD:gg2ccbar",
  "HardQCD:gg2gg",
  "HardQCD:gg2ggg",
  "HardQCD:gg2qqbar",
  "HardQCD:gg2qqbarg",
  "HardQCD:hardbbbar",
  "HardQCD:hardccbar",
  "HardQCD:qg2qg",
  "HardQCD:qg2qgg",
  "HardQCD:qg2qqqbarDiff",
  "HardQCD:qg2qqqbarSame",
  "HardQCD:qq2qq",
  "HardQCD:qq2qqgDiff",
  "HardQCD:qq2qqgSame",
  "HardQCD:qqbar2bbbar",
  "HardQCD:qqbar2ccbar",
  "HardQCD:qqbar2gg",
  "HardQCD:qqbar2ggg",
  "HardQCD:qqbar2qqbargDiff",
  "HardQCD:qqbar2qqbargSame",
  "HardQCD:qqbar2qqbarNew",
  "HiddenValley:all",
  "HiddenValley:doKinMix",
  "HiddenValley:ffbar2BvBvbar",
  "HiddenValley:ffbar2CvCvbar",
  "HiddenValley:ffbar2DvDvbar",
  "HiddenValley:ffbar2EvEvbar",
  "HiddenValley:ffbar2MUvMUvbar",
  "HiddenValley:ffbar2nuEvnuEvbar",
  "HiddenValley:ffbar2nuMUvnuMUvbar",
  "HiddenValley:ffbar2nuTAUvnuTAUvbar",
  "HiddenValley:ffbar2SvSvbar",
  "HiddenValley:ffbar2TAUvTAUvbar",
  "HiddenValley:ffbar2TvTvbar",
  "HiddenValley:ffbar2UvUvbar",
  "HiddenValley:ffbar2Zv",
  "HiddenValley:fragment",
  "HiddenValley:FSR",
  "HiddenValley:gg2BvBvbar",
  "HiddenValley:gg2CvCvbar",
  "HiddenValley:gg2DvDvbar",
  "HiddenValley:gg2SvSvbar",
  "HiddenValley:gg2TvTvbar",
  "HiddenValley:gg2UvUvbar",
  "HiddenValley:qqbar2BvBvbar",
  "HiddenValley:qqbar2CvCvbar",
  "HiddenValley:qqbar2DvDvbar",
  "HiddenValley:qqbar2SvSvbar",
  "HiddenValley:qqbar2TvTvbar",
  "HiddenValley:qqbar2UvUvbar",
  "Higgs:clipWings",
  "Higgs:cubicWidth",
  "Higgs:runningLoopMass",
  "Higgs:useBSM",
  "HiggsBSM:all",
  "HiggsBSM:allA3",
  "HiggsBSM:allH+-",
  "HiggsBSM:allH1",
  "HiggsBSM:allH2",
  "HiggsBSM:allHpair",
  "HiggsBSM:bg2H+-t",
  "HiggsBSM:ff2A3ff(t:WW)",
  "HiggsBSM:ff2A3ff(t:ZZ)",
  "HiggsBSM:ff2H1ff(t:WW)",
  "HiggsBSM:ff2H1ff(t:ZZ)",
  "HiggsBSM:ff2H2ff(t:WW)",
  "HiggsBSM:ff2H2ff(t:ZZ)",
  "HiggsBSM:ffbar2A3",
  "HiggsBSM:ffbar2A3H1",
  "HiggsBSM:ffbar2A3H2",
  "HiggsBSM:ffbar2A3W",
  "HiggsBSM:ffbar2A3Z",
  "HiggsBSM:ffbar2H+-",
  "HiggsBSM:ffbar2H+-H1",
  "HiggsBSM:ffbar2H+-H2",
  "HiggsBSM:ffbar2H+H-",
  "HiggsBSM:ffbar2H1",
  "HiggsBSM:ffbar2H1W",
  "HiggsBSM:ffbar2H1Z",
  "HiggsBSM:ffbar2H2",
  "HiggsBSM:ffbar2H2W",
  "HiggsBSM:ffbar2H2Z",
  "HiggsBSM:gg2A3",
  "HiggsBSM:gg2A3bbbar",
  "HiggsBSM:gg2A3g(l:t)",
  "HiggsBSM:gg2A3ttbar",
  "HiggsBSM:gg2H1",
  "HiggsBSM:gg2H1bbbar",
  "HiggsBSM:gg2H1g(l:t)",
  "HiggsBSM:gg2H1ttbar",
  "HiggsBSM:gg2H2",
  "HiggsBSM:gg2H2bbbar",
  "HiggsBSM:gg2H2g(l:t)",
  "HiggsBSM:gg2H2ttbar",
  "HiggsBSM:gmgm2A3",
  "HiggsBSM:gmgm2H1",
  "HiggsBSM:gmgm2H2",
  "HiggsBSM:qg2A3q",
  "HiggsBSM:qg2A3q(l:t)",
  "HiggsBSM:qg2H1q",
  "HiggsBSM:qg2H1q(l:t)",
  "HiggsBSM:qg2H2q",
  "HiggsBSM:qg2H2q(l:t)",
  "HiggsBSM:qqbar2A3bbbar",
  "HiggsBSM:qqbar2A3g(l:t)",
  "HiggsBSM:qqbar2A3ttbar",
  "HiggsBSM:qqbar2H1bbbar",
  "HiggsBSM:qqbar2H1g(l:t)",
  "HiggsBSM:qqbar2H1ttbar",
  "HiggsBSM:qqbar2H2bbbar",
  "HiggsBSM:qqbar2H2g(l:t)",
  "HiggsBSM:qqbar2H2ttbar",
  "HiggsSM:all",
  "HiggsSM:ff2Hff(t:WW)",
  "HiggsSM:ff2Hff(t:ZZ)",
  "HiggsSM:ffbar2H",
  "HiggsSM:ffbar2HW",
  "HiggsSM:ffbar2HZ",
  "HiggsSM:gg2H",
  "HiggsSM:gg2Hbbbar",
  "HiggsSM:gg2Hg(l:t)",
  "HiggsSM:gg2Httbar",
  "HiggsSM:gmgm2H",
  "HiggsSM:NLOWidths",
  "HiggsSM:qg2Hq",
  "HiggsSM:qg2Hq(l:t)",
  "HiggsSM:qqbar2Hbbbar",
  "HiggsSM:qqbar2Hg(l:t)",
  "HiggsSM:qqbar2Httbar",
  "Init:showAllParticleData",
  "Init:showAllSettings",
  "Init:showChangedParticleData",
  "Init:showChangedResonanceData",
  "Init:showChangedSettings",
  "Init:showMultipartonInteractions",
  "Init:showProcesses",
  "JetMatching:doFxFx",
  "JetMatching:doShowerKt",
  "JetMatching:merge",
  "JetMatching:setMad",
  "LeftRightSymmmetry:all",
  "LeftRightSymmmetry:ff2HLff",
  "LeftRightSymmmetry:ff2HRff",
  "LeftRightSymmmetry:ffbar2HLHL",
  "LeftRightSymmmetry:ffbar2HRHR",
  "LeftRightSymmmetry:ffbar2WR",
  "LeftRightSymmmetry:ffbar2ZR",
  "LeftRightSymmmetry:lgm2HLe",
  "LeftRightSymmmetry:lgm2HLmu",
  "LeftRightSymmmetry:lgm2HLtau",
  "LeftRightSymmmetry:lgm2HRe",
  "LeftRightSymmmetry:lgm2HRmu",
  "LeftRightSymmmetry:lgm2HRtau",
  "LeftRightSymmmetry:ll2HL",
  "LeftRightSymmmetry:ll2HR",
  "LeptoQuark:all",
  "LeptoQuark:gg2LQLQbar",
  "LeptoQuark:qg2LQl",
  "LeptoQuark:ql2LQ",
  "LeptoQuark:qqbar2LQLQbar",
  "LesHouches:matchInOut",
  "Main:LHEFskipInit",
  "Main:spareFlag1",
  "Main:spareFlag2",
  "Main:spareFlag3",
  "Merging:allowColourShuffling",
  "Merging:allowIncompleteHistoriesInReal",
  "Merging:allowSQCDClustering",
  "Merging:allowWClustering",
  "Merging:doCutBasedMerging",
  "Merging:doKTMerging",
  "Merging:doMGMerging",
  "Merging:doNL3Loop",
  "Merging:doNL3Subt",
  "Merging:doNL3Tree",
  "Merging:doPTLundMerging",
  "Merging:doUMEPSSubt",
  "Merging:doUMEPSTree",
  "Merging:doUNLOPSLoop",
  "Merging:doUNLOPSSubt",
  "Merging:doUNLOPSSubtNLO",
  "Merging:doUNLOPSTilde",
  "Merging:doUNLOPSTree",
  "Merging:doUserMerging",
  "Merging:doXSectionEstimate",
  "Merging:enforceCutOnLHE",
  "Merging:enforceStrongOrdering",
  "Merging:includeMassive",
  "Merging:includeRedundant",
  "Merging:mayRemoveDecayProducts",
  "Merging:orderInRapidity",
  "Merging:pickByFullP",
  "Merging:pickByPoPT2",
  "Merging:pickBySumPT",
  "Merging:usePythiaQFacHard",
  "Merging:usePythiaQRenHard",
  "Merging:useShowerPlugin",
  "MultipartonInteractions:allowDoubleRescatter",
  "MultipartonInteractions:allowRescatter",
  "NewGaugeBoson:ffbar2gmZZprime",
  "NewGaugeBoson:ffbar2R0",
  "NewGaugeBoson:ffbar2Wprime",
  "Next:showMothersAndDaughters",
  "Next:showScaleAndVertex",
  "Onia:all",
  "Onia:all(3DJ)",
  "Onia:all(3PJ)",
  "Onia:all(3S1)",
  "Onia:forceMassSplit",
  "ParticleDecays:allowPhotonRadiation",
  "ParticleDecays:FSRinDecays",
  "ParticleDecays:limitCylinder",
  "ParticleDecays:limitRadius",
  "ParticleDecays:limitTau",
  "ParticleDecays:limitTau0",
  "ParticleDecays:mixB",
  "PartonLevel:all",
  "PartonLevel:earlyResDec",
  "PartonLevel:FSR",
  "PartonLevel:FSRinProcess",
  "PartonLevel:FSRinResonances",
  "PartonLevel:ISR",
  "PartonLevel:MPI",
  "PartonLevel:Remnants",
  "PDF:extrapolate",
  "PDF:lepton",
  "PDF:useHard",
  "PhaseSpace:bias2Selection",
  "PhaseSpace:increaseMaximum",
  "PhaseSpace:sameForSecond",
  "PhaseSpace:showSearch",
  "PhaseSpace:showViolation",
  "PhaseSpace:useBreitWigners",
  "PhotonCollision:all",
  "PhotonCollision:gmgm2bbbar",
  "PhotonCollision:gmgm2ccbar",
  "PhotonCollision:gmgm2ee",
  "PhotonCollision:gmgm2mumu",
  "PhotonCollision:gmgm2qqbar",
  "PhotonCollision:gmgm2tautau",
  "Print:quiet",
  "ProcessLevel:all",
  "ProcessLevel:resonanceDecays",
  "PromptPhoton:all",
  "PromptPhoton:ffbar2gammagamma",
  "PromptPhoton:gg2gammagamma",
  "PromptPhoton:gg2ggamma",
  "PromptPhoton:qg2qgamma",
  "PromptPhoton:qqbar2ggamma",
  "Random:setSeed",
  "RHadrons:allow",
  "RHadrons:allowDecay",
  "RHadrons:setMasses",
  "SecondHard:Bottomonium",
  "SecondHard:Charmonium",
  "SecondHard:generate",
  "SecondHard:GmZAndJet",
  "SecondHard:PhotonAndJet",
  "SecondHard:SingleGmZ",
  "SecondHard:SingleTop",
  "SecondHard:SingleW",
  "SecondHard:TopPair",
  "SecondHard:TwoBJets",
  "SecondHard:TwoJets",
  "SecondHard:TwoPhotons",
  "SecondHard:WAndJet",
  "SigmaDiffractive:dampen",
  "SigmaElastic:setOwn",
  "SigmaProcess:bMassiveME",
  "SigmaProcess:cMassiveME",
  "SigmaProcess:muMassiveME",
  "SigmaProcess:tauMassiveME",
  "SigmaTotal:setOwn",
  "SigmaTotal:zeroAXB",
  "SLHA:allowUserOverride",
  "SLHA:keepSM",
  "SLHA:NMSSM",
  "SLHA:useDecayTable",
  "SoftQCD:all",
  "SoftQCD:centralDiffractive",
  "SoftQCD:doubleDiffractive",
  "SoftQCD:elastic",
  "SoftQCD:inelastic",
  "SoftQCD:nonDiffractive",
  "SoftQCD:singleDiffractive",
  "SpaceShower:alphaSuseCMW",
  "SpaceShower:MEafterFirst",
  "SpaceShower:MEcorrections",
  "SpaceShower:phiIntAsym",
  "SpaceShower:phiPolAsym",
  "SpaceShower:QCDshower",
  "SpaceShower:QEDshowerByL",
  "SpaceShower:QEDshowerByQ",
  "SpaceShower:rapidityOrder",
  "SpaceShower:samePTasMPI",
  "SpaceShower:useFixedFacScale",
  "SpaceShower:weakShower",
  "Stat:reset",
  "Stat:showErrors",
  "Stat:showPartonLevel",
  "Stat:showProcessLevel",
  "StringFlav:suppressLeadingB",
  "StringZ:useNonstandardB",
  "StringZ:useNonstandardC",
  "StringZ:useNonstandardH",
  "StringZ:usePetersonB",
  "StringZ:usePetersonC",
  "StringZ:usePetersonH",
  "SUSY:all",
  "SUSY:gg2gluinogluino",
  "SUSY:gg2squarkantisquark",
  "SUSY:qg2chi+-squark",
  "SUSY:qg2chi0squark",
  "SUSY:qg2squarkgluino",
  "SUSY:qq2antisquark",
  "SUSY:qq2squarksquark",
  "SUSY:qq2squarksquark:onlyQCD",
  "SUSY:qqbar2chi+-chi0",
  "SUSY:qqbar2chi+-gluino",
  "SUSY:qqbar2chi+chi-",
  "SUSY:qqbar2chi0chi0",
  "SUSY:qqbar2chi0gluino",
  "SUSY:qqbar2gluinogluino",
  "SUSY:qqbar2sleptonantislepton",
  "SUSY:qqbar2squarkantisquark",
  "SUSY:qqbar2squarkantisquark:onlyQCD",
  "SUSYResonance:3BodyMatrixElement",
  "TimeShower:allowBeamRecoil",
  "TimeShower:allowMPIdipole",
  "TimeShower:alphaSuseCMW",
  "TimeShower:dampenBeamRecoil",
  "TimeShower:globalRecoil",
  "TimeShower:interleave",
  "TimeShower:limitPTmaxGlobal",
  "TimeShower:MEafterFirst",
  "TimeShower:MEcorrections",
  "TimeShower:phiPolAsym",
  "TimeShower:QCDshower",
  "TimeShower:QEDshowerByGamma",
  "TimeShower:QEDshowerByL",
  "TimeShower:QEDshowerByQ",
  "TimeShower:recoilToColoured",
  "TimeShower:useFixedFacScale",
  "TimeShower:weakShower",
  "Top:all",
  "Top:ffbar2tqbar(s:W)",
  "Top:ffbar2ttbar(s:gmZ)",
  "Top:gg2ttbar",
  "Top:gmgm2ttbar",
  "Top:qq2tq(t:W)",
  "Top:qqbar2ttbar",
  "WeakBosonAndParton:all",
  "WeakBosonAndParton:ffbar2gmZgm",
  "WeakBosonAndParton:ffbar2Wgm",
  "WeakBosonAndParton:fgm2gmZf",
  "WeakBosonAndParton:fgm2Wf",
  "WeakBosonAndParton:qg2gmZq",
  "WeakBosonAndParton:qg2Wq",
  "WeakBosonAndParton:qqbar2gmZg",
  "WeakBosonAndParton:qqbar2Wg",
  "WeakBosonExchange:all",
  "WeakBosonExchange:ff2ff(t:gmZ)",
  "WeakBosonExchange:ff2ff(t:W)",
  "WeakDoubleBoson:all",
  "WeakDoubleBoson:ffbar2gmZgmZ",
  "WeakDoubleBoson:ffbar2WW",
  "WeakDoubleBoson:ffbar2ZW",
  "WeakShower:singleEmission",
  "WeakShower:vetoQCDjets",
  "WeakShower:vetoWeakJets",
  "WeakSingleBoson:all",
  "WeakSingleBoson:ffbar2ffbar(s:gm)",
  "WeakSingleBoson:ffbar2ffbar(s:gmZ)",
  "WeakSingleBoson:ffbar2ffbar(s:W)",
  "WeakSingleBoson:ffbar2gmZ",
  "WeakSingleBoson:ffbar2W",
  "Zprime:coup2gen4",
  "Zprime:universality",
]

Mode = [  "BeamRemnants:companionPower",
  "BeamRemnants:maxValQuark",
  "BeamRemnants:remnantMode",
  "Beams:frameType",
  "Beams:idA",
  "Beams:idB",
  "Beams:nSkipLHEFatInit",
  "Check:levelParticleData",
  "Check:nErrList",
  "ColourReconnection:flipMode",
  "ColourReconnection:lambdaForm",
  "ColourReconnection:mode",
  "ColourReconnection:nColours",
  "ColourReconnection:timeDilationMode",
  "ContactInteractions:etaLL",
  "ContactInteractions:etaLR",
  "ContactInteractions:etaRR",
  "ContactInteractions:nQuarkNew",
  "Diffraction:bProfile",
  "Diffraction:PomFlux",
  "Diffraction:sampleType",
  "Event:startColTag",
  "ExtraDimensionsG*:KKintMode",
  "ExtraDimensionsLED:CutOffMode",
  "ExtraDimensionsLED:n",
  "ExtraDimensionsLED:NegInt",
  "ExtraDimensionsLED:nQuarkNew",
  "ExtraDimensionsLED:opMode",
  "ExtraDimensionsTEV:gmZmode",
  "ExtraDimensionsTEV:nMax",
  "ExtraDimensionsUnpart:CutOffMode",
  "ExtraDimensionsUnpart:gXX",
  "ExtraDimensionsUnpart:gXY",
  "ExtraDimensionsUnpart:spinU",
  "HadronScatter:hadronSelect",
  "HadronScatter:scatterProb",
  "HardQCD:nQuarkNew",
  "HiddenValley:nFlav",
  "HiddenValley:Ngauge",
  "HiddenValley:spinFv",
  "HiddenValley:spinqv",
  "HiggsA3:parity",
  "HiggsH1:parity",
  "HiggsH2:parity",
  "Init:showOneParticleData",
  "JetMatching:exclusive",
  "JetMatching:jetAlgorithm",
  "JetMatching:jetAllow",
  "JetMatching:jetMatch",
  "JetMatching:nEta",
  "JetMatching:nJet",
  "JetMatching:nJetMax",
  "JetMatching:nPartonsNow",
  "JetMatching:nPhi",
  "JetMatching:nQmatch",
  "JetMatching:scheme",
  "JetMatching:slowJetPower",
  "LesHouches:idRenameBeams",
  "LesHouches:setLeptonMass",
  "LesHouches:setLifetime",
  "Main:numberOfEvents",
  "Main:numberOfSubruns",
  "Main:spareMode1",
  "Main:spareMode2",
  "Main:spareMode3",
  "Main:subrun",
  "Main:timesAllowErrors",
  "Merging:incompleteScalePrescrip",
  "Merging:ktType",
  "Merging:nJetMax",
  "Merging:nJetMaxNLO",
  "Merging:nQuarksMerge",
  "Merging:nRecluster",
  "Merging:nRequested",
  "Merging:unorderedASscalePrescrip",
  "Merging:unorderedPDFscalePrescrip",
  "Merging:unorderedScalePrescrip",
  "MiniStringFragmentation:nTry",
  "MultipartonInteractions:alphaEMorder",
  "MultipartonInteractions:alphaSorder",
  "MultipartonInteractions:bProfile",
  "MultipartonInteractions:bSelScale",
  "MultipartonInteractions:enhanceScreening",
  "MultipartonInteractions:nQuarkIn",
  "MultipartonInteractions:nSample",
  "MultipartonInteractions:processLevel",
  "MultipartonInteractions:pTmaxMatch",
  "MultipartonInteractions:rescatterMode",
  "Next:numberCount",
  "Next:numberShowEvent",
  "Next:numberShowInfo",
  "Next:numberShowLHA",
  "Next:numberShowProcess",
  "ParticleData:modeBreitWigner",
  "PDF:PomSet",
  "PDFinProcess:nQuarkIn",
  "POWHEG:emitted",
  "POWHEG:MPIveto",
  "POWHEG:nFinal",
  "POWHEG:pTdef",
  "POWHEG:pTemt",
  "POWHEG:pThard",
  "POWHEG:QEDveto",
  "POWHEG:veto",
  "POWHEG:vetoCount",
  "PromptPhoton:nQuarkLoop",
  "Pythia:versionDate",
  "Random:seed",
  "RHadrons:idGluino",
  "RHadrons:idSbottom",
  "RHadrons:idStop",
  "SigmaProcess:alphaEMorder",
  "SigmaProcess:alphaSorder",
  "SigmaProcess:factorScale1",
  "SigmaProcess:factorScale2",
  "SigmaProcess:factorScale3",
  "SigmaProcess:factorScale3VV",
  "SigmaProcess:renormScale1",
  "SigmaProcess:renormScale2",
  "SigmaProcess:renormScale3",
  "SigmaProcess:renormScale3VV",
  "SLHA:meMode",
  "SLHA:readFrom",
  "SLHA:verbose",
  "SpaceShower:alphaEMorder",
  "SpaceShower:alphaSorder",
  "SpaceShower:nQuarkIn",
  "SpaceShower:pTdampMatch",
  "SpaceShower:pTmaxMatch",
  "SpaceShower:weakShowerMode",
  "StandardModel:alphaSnfmax",
  "SUSY:idA",
  "SUSY:idB",
  "SUSY:sin2thetaWMode",
  "TauDecays:externalMode",
  "TauDecays:mode",
  "TauDecays:tauMother",
  "TimeShower:alphaEMorder",
  "TimeShower:alphaSorder",
  "TimeShower:globalRecoilMode",
  "TimeShower:nGammaToLepton",
  "TimeShower:nGammaToQuark",
  "TimeShower:nGluonToQuark",
  "TimeShower:nMaxGlobalBranch",
  "TimeShower:nMaxGlobalRecoil",
  "TimeShower:nPartonsInBorn",
  "TimeShower:pTdampMatch",
  "TimeShower:pTmaxMatch",
  "TimeShower:weakShowerMode",
  "TimeShower:weightGluonToQuark",
  "Tune:ee",
  "Tune:pp",
  "Tune:preferLHAPDF",
  "WeakZ0:gmZmode",
  "Zprime:gmZmode",
]

Param = [  "BeamRemnants:gluonPower",
  "BeamRemnants:halfMassForKT",
  "BeamRemnants:halfScaleForKT",
  "BeamRemnants:primordialKThard",
  "BeamRemnants:primordialKTremnant",
  "BeamRemnants:primordialKTsoft",
  "BeamRemnants:reducedKTatHighY",
  "BeamRemnants:saturation",
  "BeamRemnants:valenceDiqEnhance",
  "BeamRemnants:valencePowerDinP",
  "BeamRemnants:valencePowerMeson",
  "BeamRemnants:valencePowerUinP",
  "BeamRemnants:xGluonCutoff",
  "Beams:eA",
  "Beams:eB",
  "Beams:eCM",
  "Beams:maxDevA",
  "Beams:maxDevB",
  "Beams:maxDevTime",
  "Beams:maxDevVertex",
  "Beams:offsetTime",
  "Beams:offsetVertexX",
  "Beams:offsetVertexY",
  "Beams:offsetVertexZ",
  "Beams:pxA",
  "Beams:pxB",
  "Beams:pyA",
  "Beams:pyB",
  "Beams:pzA",
  "Beams:pzB",
  "Beams:sigmaPxA",
  "Beams:sigmaPxB",
  "Beams:sigmaPyA",
  "Beams:sigmaPyB",
  "Beams:sigmaPzA",
  "Beams:sigmaPzB",
  "Beams:sigmaTime",
  "Beams:sigmaVertexX",
  "Beams:sigmaVertexY",
  "Beams:sigmaVertexZ",
  "BoseEinstein:lambda",
  "BoseEinstein:QRef",
  "BoseEinstein:widthSep",
  "Check:epTolErr",
  "Check:epTolWarn",
  "Check:mTolErr",
  "Check:mTolWarn",
  "ColourReconnection:blowR",
  "ColourReconnection:blowT",
  "ColourReconnection:dLambdaCut",
  "ColourReconnection:fracGluon",
  "ColourReconnection:fragmentationTime",
  "ColourReconnection:junctionCorrection",
  "ColourReconnection:kI",
  "ColourReconnection:m0",
  "ColourReconnection:m2Lambda",
  "ColourReconnection:range",
  "ColourReconnection:rHadron",
  "ColourReconnection:timeDilationPar",
  "ContactInteractions:Lambda",
  "Diffraction:coreFraction",
  "Diffraction:coreRadius",
  "Diffraction:expPow",
  "Diffraction:largeMassSuppress",
  "Diffraction:MBRalpha",
  "Diffraction:MBRbeta0",
  "Diffraction:MBRdyminCD",
  "Diffraction:MBRdyminCDflux",
  "Diffraction:MBRdyminDD",
  "Diffraction:MBRdyminDDflux",
  "Diffraction:MBRdyminSD",
  "Diffraction:MBRdyminSDflux",
  "Diffraction:MBRdyminSigCD",
  "Diffraction:MBRdyminSigDD",
  "Diffraction:MBRdyminSigSD",
  "Diffraction:MBRepsilon",
  "Diffraction:MBRm2Min",
  "Diffraction:MBRsigma0",
  "Diffraction:mMinPert",
  "Diffraction:mPowPomP",
  "Diffraction:mRefPomP",
  "Diffraction:mWidthPert",
  "Diffraction:pickQuarkNorm",
  "Diffraction:pickQuarkPower",
  "Diffraction:PomFluxAlphaPrime",
  "Diffraction:PomFluxEpsilon",
  "Diffraction:primKTwidth",
  "Diffraction:probMaxPert",
  "Diffraction:sigmaRefPomP",
  "ExcitedFermion:contactDec",
  "ExcitedFermion:coupF",
  "ExcitedFermion:coupFcol",
  "ExcitedFermion:coupFprime",
  "ExcitedFermion:Lambda",
  "ExtraDimensionsG*:Gbb",
  "ExtraDimensionsG*:Ggg",
  "ExtraDimensionsG*:Ggmgm",
  "ExtraDimensionsG*:Ghh",
  "ExtraDimensionsG*:Gll",
  "ExtraDimensionsG*:Gqq",
  "ExtraDimensionsG*:Gtt",
  "ExtraDimensionsG*:GWW",
  "ExtraDimensionsG*:GZZ",
  "ExtraDimensionsG*:kappaMG",
  "ExtraDimensionsG*:KKgbL",
  "ExtraDimensionsG*:KKgbR",
  "ExtraDimensionsG*:KKgqL",
  "ExtraDimensionsG*:KKgqR",
  "ExtraDimensionsG*:KKgtL",
  "ExtraDimensionsG*:KKgtR",
  "ExtraDimensionsLED:c",
  "ExtraDimensionsLED:g",
  "ExtraDimensionsLED:LambdaT",
  "ExtraDimensionsLED:MD",
  "ExtraDimensionsLED:t",
  "ExtraDimensionsTEV:mStar",
  "ExtraDimensionsUnpart:dU",
  "ExtraDimensionsUnpart:lambda",
  "ExtraDimensionsUnpart:LambdaU",
  "ExtraDimensionsUnpart:ratio",
  "FourthGeneration:VcbPrime",
  "FourthGeneration:VtbPrime",
  "FourthGeneration:VtPrimeb",
  "FourthGeneration:VtPrimebPrime",
  "FourthGeneration:VtPrimed",
  "FourthGeneration:VtPrimes",
  "FourthGeneration:VubPrime",
  "FragmentationSystems:mJoin",
  "FragmentationSystems:mJoinJunction",
  "HadronLevel:mStringMin",
  "HadronScatter:j",
  "HadronScatter:k",
  "HadronScatter:N",
  "HadronScatter:p",
  "HadronScatter:rMax",
  "HiddenValley:alphaFSR",
  "HiddenValley:aLund",
  "HiddenValley:bmqv2",
  "HiddenValley:kappa",
  "HiddenValley:kinMix",
  "HiddenValley:probVector",
  "HiddenValley:pTminFSR",
  "HiddenValley:rFactqv",
  "HiddenValley:sigmamqv",
  "Higgs:wingsFac",
  "HiggsA3:coup2d",
  "HiggsA3:coup2H1H1",
  "HiggsA3:coup2H1Z",
  "HiggsA3:coup2H2Z",
  "HiggsA3:coup2Hchg",
  "HiggsA3:coup2HchgW",
  "HiggsA3:coup2l",
  "HiggsA3:coup2u",
  "HiggsA3:coup2W",
  "HiggsA3:coup2Z",
  "HiggsA3:etaParity",
  "HiggsA3:phiParity",
  "HiggsH1:coup2d",
  "HiggsH1:coup2Hchg",
  "HiggsH1:coup2l",
  "HiggsH1:coup2u",
  "HiggsH1:coup2W",
  "HiggsH1:coup2Z",
  "HiggsH1:etaParity",
  "HiggsH1:phiParity",
  "HiggsH2:coup2A3A3",
  "HiggsH2:coup2A3H1",
  "HiggsH2:coup2d",
  "HiggsH2:coup2H1H1",
  "HiggsH2:coup2H1Z",
  "HiggsH2:coup2Hchg",
  "HiggsH2:coup2HchgW",
  "HiggsH2:coup2l",
  "HiggsH2:coup2u",
  "HiggsH2:coup2W",
  "HiggsH2:coup2Z",
  "HiggsH2:etaParity",
  "HiggsH2:phiParity",
  "HiggsHchg:coup2H1W",
  "HiggsHchg:coup2H2W",
  "HiggsHchg:tanBeta",
  "JetMatching:clFact",
  "JetMatching:coneMatchHeavy",
  "JetMatching:coneMatchLight",
  "JetMatching:coneRadius",
  "JetMatching:coneRadiusHeavy",
  "JetMatching:etaJetMax",
  "JetMatching:eTjetMin",
  "JetMatching:eTseed",
  "JetMatching:eTthreshold",
  "JetMatching:qCut",
  "JetMatching:qCutME",
  "LeftRightSymmmetry:coupHee",
  "LeftRightSymmmetry:coupHmue",
  "LeftRightSymmmetry:coupHmumu",
  "LeftRightSymmmetry:coupHtaue",
  "LeftRightSymmmetry:coupHtaumu",
  "LeftRightSymmmetry:coupHtautau",
  "LeftRightSymmmetry:gL",
  "LeftRightSymmmetry:gR",
  "LeftRightSymmmetry:vL",
  "LeptoQuark:kCoup",
  "LesHouches:mRecalculate",
  "Main:spareParm1",
  "Main:spareParm2",
  "Main:spareParm3",
  "Merging:aCollFSR",
  "Merging:aCollISR",
  "Merging:Dparameter",
  "Merging:dRijMS",
  "Merging:fsrInRecNorm",
  "Merging:kFactor0j",
  "Merging:kFactor1j",
  "Merging:kFactor2j",
  "Merging:muFac",
  "Merging:muFacInME",
  "Merging:muRen",
  "Merging:muRenInME",
  "Merging:nonJoinedNorm",
  "Merging:pTiMS",
  "Merging:QijMS",
  "Merging:scaleSeparationFactor",
  "Merging:TMS",
  "MultipartonInteractions:a1",
  "MultipartonInteractions:alphaSvalue",
  "MultipartonInteractions:coreFraction",
  "MultipartonInteractions:coreRadius",
  "MultipartonInteractions:deltaYRescatter",
  "MultipartonInteractions:ecmPow",
  "MultipartonInteractions:ecmRef",
  "MultipartonInteractions:expPow",
  "MultipartonInteractions:Kfactor",
  "MultipartonInteractions:pT0Ref",
  "MultipartonInteractions:pTmin",
  "MultipartonInteractions:ySepRescatter",
  "Onia:massSplit",
  "ParticleData:alphaSvalueMRun",
  "ParticleData:maxEnhanceBW",
  "ParticleData:mbRun",
  "ParticleData:mcRun",
  "ParticleData:mdRun",
  "ParticleData:msRun",
  "ParticleData:mtRun",
  "ParticleData:muRun",
  "ParticleDecays:colRearrange",
  "ParticleDecays:mSafety",
  "ParticleDecays:multGoffset",
  "ParticleDecays:multIncrease",
  "ParticleDecays:multIncreaseWeak",
  "ParticleDecays:multRefMass",
  "ParticleDecays:rMax",
  "ParticleDecays:sigmaSoft",
  "ParticleDecays:tau0Max",
  "ParticleDecays:tauMax",
  "ParticleDecays:xBdMix",
  "ParticleDecays:xBsMix",
  "ParticleDecays:xyMax",
  "ParticleDecays:zMax",
  "PDF:PomGluonA",
  "PDF:PomGluonB",
  "PDF:PomQuarkA",
  "PDF:PomQuarkB",
  "PDF:PomQuarkFrac",
  "PDF:PomRescale",
  "PDF:PomStrangeSupp",
  "PhaseSpace:bias2SelectionPow",
  "PhaseSpace:bias2SelectionRef",
  "PhaseSpace:mHatMax",
  "PhaseSpace:mHatMaxSecond",
  "PhaseSpace:mHatMin",
  "PhaseSpace:mHatMinSecond",
  "PhaseSpace:minWidthBreitWigners",
  "PhaseSpace:pTHat3Max",
  "PhaseSpace:pTHat3Min",
  "PhaseSpace:pTHat5Max",
  "PhaseSpace:pTHat5Min",
  "PhaseSpace:pTHatMax",
  "PhaseSpace:pTHatMaxSecond",
  "PhaseSpace:pTHatMin",
  "PhaseSpace:pTHatMinDiverge",
  "PhaseSpace:pTHatMinSecond",
  "PhaseSpace:RsepMin",
  "Pythia:versionNumber",
  "ResonanceWidths:minThreshold",
  "ResonanceWidths:minWidth",
  "RHadrons:diquarkSpin1",
  "RHadrons:maxWidth",
  "RHadrons:mCollapse",
  "RHadrons:mOffsetCloud",
  "RHadrons:probGluinoball",
  "SigmaDiffractive:maxAX",
  "SigmaDiffractive:maxAXB",
  "SigmaDiffractive:maxXB",
  "SigmaDiffractive:maxXX",
  "SigmaElastic:bSlope",
  "SigmaElastic:lambda",
  "SigmaElastic:phaseConst",
  "SigmaElastic:rho",
  "SigmaElastic:tAbsMin",
  "SigmaProcess:alphaSvalue",
  "SigmaProcess:factorFixScale",
  "SigmaProcess:factorMultFac",
  "SigmaProcess:Kfactor",
  "SigmaProcess:renormFixScale",
  "SigmaProcess:renormMultFac",
  "SigmaTotal:sigmaAX",
  "SigmaTotal:sigmaAXB",
  "SigmaTotal:sigmaAXB2TeV",
  "SigmaTotal:sigmaEl",
  "SigmaTotal:sigmaTot",
  "SigmaTotal:sigmaXB",
  "SigmaTotal:sigmaXX",
  "SLHA:minMassSM",
  "SpaceShower:alphaSvalue",
  "SpaceShower:ecmPow",
  "SpaceShower:ecmRef",
  "SpaceShower:factorMultFac",
  "SpaceShower:fixedFacScale",
  "SpaceShower:pT0Ref",
  "SpaceShower:pTdampFudge",
  "SpaceShower:pTmaxFudge",
  "SpaceShower:pTmaxFudgeMPI",
  "SpaceShower:pTmin",
  "SpaceShower:pTminChgL",
  "SpaceShower:pTminChgQ",
  "SpaceShower:pTminWeak",
  "SpaceShower:renormMultFac",
  "SpaceShower:strengthIntAsym",
  "StandardModel:alphaEM0",
  "StandardModel:alphaEMmZ",
  "StandardModel:GF",
  "StandardModel:sin2thetaW",
  "StandardModel:sin2thetaWbar",
  "StandardModel:Vcb",
  "StandardModel:Vcd",
  "StandardModel:Vcs",
  "StandardModel:Vtb",
  "StandardModel:Vtd",
  "StandardModel:Vts",
  "StandardModel:Vub",
  "StandardModel:Vud",
  "StandardModel:Vus",
  "StringFlav:decupletSup",
  "StringFlav:etaPrimeSup",
  "StringFlav:etaSup",
  "StringFlav:heavyLeadingBSup",
  "StringFlav:lightLeadingBSup",
  "StringFlav:mesonBL1S0J1",
  "StringFlav:mesonBL1S1J0",
  "StringFlav:mesonBL1S1J1",
  "StringFlav:mesonBL1S1J2",
  "StringFlav:mesonBvector",
  "StringFlav:mesonCL1S0J1",
  "StringFlav:mesonCL1S1J0",
  "StringFlav:mesonCL1S1J1",
  "StringFlav:mesonCL1S1J2",
  "StringFlav:mesonCvector",
  "StringFlav:mesonSL1S0J1",
  "StringFlav:mesonSL1S1J0",
  "StringFlav:mesonSL1S1J1",
  "StringFlav:mesonSL1S1J2",
  "StringFlav:mesonSvector",
  "StringFlav:mesonUDL1S0J1",
  "StringFlav:mesonUDL1S1J0",
  "StringFlav:mesonUDL1S1J1",
  "StringFlav:mesonUDL1S1J2",
  "StringFlav:mesonUDvector",
  "StringFlav:popcornRate",
  "StringFlav:popcornSmeson",
  "StringFlav:popcornSpair",
  "StringFlav:probQQ1toQQ0",
  "StringFlav:probQQtoQ",
  "StringFlav:probSQtoQQ",
  "StringFlav:probStoUD",
  "StringFlav:thetaL1S0J1",
  "StringFlav:thetaL1S1J0",
  "StringFlav:thetaL1S1J1",
  "StringFlav:thetaL1S1J2",
  "StringFlav:thetaPS",
  "StringFlav:thetaV",
  "StringFragmentation:eBothLeftJunction",
  "StringFragmentation:eMaxLeftJunction",
  "StringFragmentation:eMinLeftJunction",
  "StringFragmentation:eNormJunction",
  "StringFragmentation:stopMass",
  "StringFragmentation:stopNewFlav",
  "StringFragmentation:stopSmear",
  "StringPT:enhancedFraction",
  "StringPT:enhancedWidth",
  "StringPT:sigma",
  "StringZ:aExtraDiquark",
  "StringZ:aExtraSQuark",
  "StringZ:aLund",
  "StringZ:aNonstandardB",
  "StringZ:aNonstandardC",
  "StringZ:aNonstandardH",
  "StringZ:bLund",
  "StringZ:bNonstandardB",
  "StringZ:bNonstandardC",
  "StringZ:bNonstandardH",
  "StringZ:epsilonB",
  "StringZ:epsilonC",
  "StringZ:epsilonH",
  "StringZ:rFactB",
  "StringZ:rFactC",
  "StringZ:rFactH",
  "TauDecays:tauPolarization",
  "TimeShower:alphaSvalue",
  "TimeShower:factorMultFac",
  "TimeShower:fixedFacScale",
  "TimeShower:mMaxGamma",
  "TimeShower:octetOniumColFac",
  "TimeShower:octetOniumFraction",
  "TimeShower:pTdampFudge",
  "TimeShower:pTmaxFudge",
  "TimeShower:pTmaxFudgeMPI",
  "TimeShower:pTmin",
  "TimeShower:pTminChgL",
  "TimeShower:pTminChgQ",
  "TimeShower:pTminWeak",
  "TimeShower:renormMultFac",
  "TimeShower:scaleGluonToQuark",
  "WeakShower:enhancement",
  "WeakShower:vetoWeakDeltaR",
  "Wprime:al",
  "Wprime:anglesWZ",
  "Wprime:aq",
  "Wprime:coup2WZ",
  "Wprime:vl",
  "Wprime:vq",
  "Zprime:ab",
  "Zprime:abPrime",
  "Zprime:ac",
  "Zprime:ad",
  "Zprime:ae",
  "Zprime:amu",
  "Zprime:anglesWW",
  "Zprime:anue",
  "Zprime:anumu",
  "Zprime:anutau",
  "Zprime:anutauPrime",
  "Zprime:as",
  "Zprime:at",
  "Zprime:atau",
  "Zprime:atauPrime",
  "Zprime:atPrime",
  "Zprime:au",
  "Zprime:coup2WW",
  "Zprime:vb",
  "Zprime:vbPrime",
  "Zprime:vc",
  "Zprime:vd",
  "Zprime:ve",
  "Zprime:vmu",
  "Zprime:vnue",
  "Zprime:vnumu",
  "Zprime:vnutau",
  "Zprime:vnutauPrime",
  "Zprime:vs",
  "Zprime:vt",
  "Zprime:vtau",
  "Zprime:vtauPrime",
  "Zprime:vtPrime",
  "Zprime:vu",
]

Word = [  "Alpgen:file",
  "Beams:LHEF",
  "Beams:LHEFheader",
  "Main:spareWord1",
  "Main:spareWord2",
  "Main:spareWord3",
  "Merging:Process",
  "PDF:pHardSet",
  "PDF:pHardSetB",
  "PDF:piSet",
  "PDF:piSetB",
  "PDF:pSet",
  "PDF:pSetB",
  "SLHA:file",
]

FlagList = [  "Bottomonium:gg2bbbar(3DJ)[3DJ(1)]g",
  "Bottomonium:gg2bbbar(3DJ)[3PJ(8)]g",
  "Bottomonium:gg2bbbar(3PJ)[3PJ(1)]g",
  "Bottomonium:gg2bbbar(3PJ)[3S1(8)]g",
  "Bottomonium:gg2bbbar(3S1)[1S0(8)]g",
  "Bottomonium:gg2bbbar(3S1)[3PJ(8)]g",
  "Bottomonium:gg2bbbar(3S1)[3S1(1)]g",
  "Bottomonium:gg2bbbar(3S1)[3S1(8)]g",
  "Bottomonium:qg2bbbar(3DJ)[3PJ(8)]q",
  "Bottomonium:qg2bbbar(3PJ)[3PJ(1)]q",
  "Bottomonium:qg2bbbar(3PJ)[3S1(8)]q",
  "Bottomonium:qg2bbbar(3S1)[1S0(8)]q",
  "Bottomonium:qg2bbbar(3S1)[3PJ(8)]q",
  "Bottomonium:qg2bbbar(3S1)[3S1(8)]q",
  "Bottomonium:qqbar2bbbar(3DJ)[3PJ(8)]g",
  "Bottomonium:qqbar2bbbar(3PJ)[3PJ(1)]g",
  "Bottomonium:qqbar2bbbar(3PJ)[3S1(8)]g",
  "Bottomonium:qqbar2bbbar(3S1)[1S0(8)]g",
  "Bottomonium:qqbar2bbbar(3S1)[3PJ(8)]g",
  "Bottomonium:qqbar2bbbar(3S1)[3S1(8)]g",
  "Charmonium:gg2ccbar(3DJ)[3DJ(1)]g",
  "Charmonium:gg2ccbar(3DJ)[3PJ(8)]g",
  "Charmonium:gg2ccbar(3PJ)[3PJ(1)]g",
  "Charmonium:gg2ccbar(3PJ)[3S1(8)]g",
  "Charmonium:gg2ccbar(3S1)[1S0(8)]g",
  "Charmonium:gg2ccbar(3S1)[3PJ(8)]g",
  "Charmonium:gg2ccbar(3S1)[3S1(1)]g",
  "Charmonium:gg2ccbar(3S1)[3S1(8)]g",
  "Charmonium:qg2ccbar(3DJ)[3PJ(8)]q",
  "Charmonium:qg2ccbar(3PJ)[3PJ(1)]q",
  "Charmonium:qg2ccbar(3PJ)[3S1(8)]q",
  "Charmonium:qg2ccbar(3S1)[1S0(8)]q",
  "Charmonium:qg2ccbar(3S1)[3PJ(8)]q",
  "Charmonium:qg2ccbar(3S1)[3S1(8)]q",
  "Charmonium:qqbar2ccbar(3DJ)[3PJ(8)]g",
  "Charmonium:qqbar2ccbar(3PJ)[3PJ(1)]g",
  "Charmonium:qqbar2ccbar(3PJ)[3S1(8)]g",
  "Charmonium:qqbar2ccbar(3S1)[1S0(8)]g",
  "Charmonium:qqbar2ccbar(3S1)[3PJ(8)]g",
  "Charmonium:qqbar2ccbar(3S1)[3S1(8)]g",
]

ModeList = [  "Bottomonium:states(3DJ)",
  "Bottomonium:states(3PJ)",
  "Bottomonium:states(3S1)",
  "Charmonium:states(3DJ)",
  "Charmonium:states(3PJ)",
  "Charmonium:states(3S1)",
  "SUSY:idVecA",
  "SUSY:idVecB",
]

ParamList = [  "Bottomonium:O(3DJ)[3D1(1)]",
  "Bottomonium:O(3DJ)[3P0(8)]",
  "Bottomonium:O(3PJ)[3P0(1)]",
  "Bottomonium:O(3PJ)[3S1(8)]",
  "Bottomonium:O(3S1)[1S0(8)]",
  "Bottomonium:O(3S1)[3P0(8)]",
  "Bottomonium:O(3S1)[3S1(1)]",
  "Bottomonium:O(3S1)[3S1(8)]",
  "Charmonium:O(3DJ)[3D1(1)]",
  "Charmonium:O(3DJ)[3P0(8)]",
  "Charmonium:O(3PJ)[3P0(1)]",
  "Charmonium:O(3PJ)[3S1(8)]",
  "Charmonium:O(3S1)[1S0(8)]",
  "Charmonium:O(3S1)[3P0(8)]",
  "Charmonium:O(3S1)[3S1(1)]",
  "Charmonium:O(3S1)[3S1(8)]",
  "StringFlav:probQQ1toQQ0join",
]

import regex as re
import os

def format(s):
  s = re.sub(r'[:\(\)\[\]"]', "_", s)
  s = re.sub(r'\+', "plus", s)
  s = re.sub(r'\-', "minus", s)
  s = re.sub(r'\*', "star", s)
  return s

Flag_dict = { }
Mode_dict = { }
Param_dict = { }
Word_dict = { }
FlagList_dict = { }
ModeList_dict = { }
ParamList_dict = { }

for subdir, dirs, files in os.walk('.'):
    for file in files:
      if file.endswith(".cc") or file.endswith(".h"):
        print(file)
        f = open(subdir + "/" + file,"r")
        s = f.read()
        sorig = s
        f.close()

        def fsub(m): return m.group(1) + m.group(2) + "set(Flag::" + format(m.group(3)) + ", " + m.group(4) + ")"
        def msub(m): return m.group(1) + m.group(2) + "set(Mode::" + format(m.group(3)) + ", " + m.group(4) + ")"
        def psub(m): return m.group(1) + m.group(2) + "set(Param::" + format(m.group(3)) + ", " + m.group(4) + ")"
        def wsub(m): return m.group(1) + m.group(2) + "set(Word::" + format(m.group(3)) + ", " + m.group(4) + ")"
        def flsub(m): return m.group(1) + m.group(2) + "set(FlagList::" + format(m.group(3)) + ", " + m.group(4) + ")"
        def mlsub(m): return m.group(1) + m.group(2) + "set(ModeList::" + format(m.group(3)) + ", " + m.group(4) + ")"
        def plsub(m): return m.group(1) + m.group(2) + "set(ParamList::" + format(m.group(3)) + ", " + m.group(4) + ")"

        # settingsPtr->flag("name:name", value)
        s = re.sub(r'(settingsPtr|settings) *(\.|->) *flag *\(\s*"(.*?)" *, *(.*?) *\)', fsub, s)
        s = re.sub(r'(settingsPtr|settings) *(\.|->) *mode *\(\s*"(.*?)" *, *(.*?) *\)', msub, s)
        s = re.sub(r'(settingsPtr|settings) *(\.|->) *parm *\(\s*"(.*?)" *, *(.*?) *\)', psub, s)
        s = re.sub(r'(settingsPtr|settings) *(\.|->) *word *\(\s*"(.*?)" *, *(.*?) *\)', wsub, s)
        s = re.sub(r'(settingsPtr|settings) *(\.|->) *fvec *\(\s*"(.*?)" *, *(.*?) *\)', flsub, s)
        s = re.sub(r'(settingsPtr|settings) *(\.|->) *mvec *\(\s*"(.*?)" *, *(.*?) *\)', mlsub, s)
        s = re.sub(r'(settingsPtr|settings) *(\.|->) *pvec *\(\s*"(.*?)" *, *(.*?) *\)', plsub, s)

        def fsub2(m): return m.group(1) + m.group(2) + "get(Flag::" + format(m.group(3)) + ")"
        def msub2(m): return m.group(1) + m.group(2) + "get(Mode::" + format(m.group(3)) + ")"
        def psub2(m): return m.group(1) + m.group(2) + "get(Param::" + format(m.group(3)) + ")"
        def wsub2(m): return m.group(1) + m.group(2) + "get(Word::" + format(m.group(3)) + ")"
        def flsub2(m): return m.group(1) + m.group(2) + "get(FlagList::" + format(m.group(3)) + ")"
        def mlsub2(m): return m.group(1) + m.group(2) + "get(ModeList::" + format(m.group(3)) + ")"
        def plsub2(m): return m.group(1) + m.group(2) + "get(ParamList::" + format(m.group(3)) + ")"

        # settingsPtr->flag("name:name")
        s = re.sub(r'(settingsPtr|settings) *(\.|->) *flag *\(\s*"(.*?)" *\)', fsub2, s)
        s = re.sub(r'(settingsPtr|settings) *(\.|->) *mode *\(\s*"(.*?)" *\)', msub2, s)
        s = re.sub(r'(settingsPtr|settings) *(\.|->) *parm *\(\s*"(.*?)" *\)', psub2, s)
        s = re.sub(r'(settingsPtr|settings) *(\.|->) *word *\(\s*"(.*?)" *\)', wsub2, s)
        s = re.sub(r'(settingsPtr|settings) *(\.|->) *fvec *\(\s*"(.*?)" *\)', flsub2, s)
        s = re.sub(r'(settingsPtr|settings) *(\.|->) *mvec *\(\s*"(.*?)" *\)', mlsub2, s)
        s = re.sub(r'(settingsPtr|settings) *(\.|->) *pvec *\(\s*"(.*?)" *\)', plsub2, s)

        def fsub3(m): return m.group(1) + m.group(2) + "get(Flag::" + format(m.group(3)) + ")"
        def msub3(m): return m.group(1) + m.group(2) + "get(Mode::" + format(m.group(3)) + ")"
        def psub3(m): return m.group(1) + m.group(2) + "get(Param::" + format(m.group(3)) + ")"
        def wsub3(m): return m.group(1) + m.group(2) + "get(Word::" + format(m.group(3)) + ")"
        def flsub3(m): return m.group(1) + m.group(2) + "get(FlagList::" + format(m.group(3)) + ")"
        def mlsub3(m): return m.group(1) + m.group(2) + "get(ModeList::" + format(m.group(3)) + ")"
        def plsub3(m): return m.group(1) + m.group(2) + "get(ParamList::" + format(m.group(3)) + ")"

        # pythia.flag("name:name")
        s = re.sub(r'(pythiaPtr|pythia) *(\.|->) *flag *\(\s*"(.*?)" *\)', fsub3, s)
        s = re.sub(r'(pythiaPtr|pythia) *(\.|->) *mode *\(\s*"(.*?)" *\)', msub3, s)
        s = re.sub(r'(pythiaPtr|pythia) *(\.|->) *parm *\(\s*"(.*?)" *\)', psub3, s)
        s = re.sub(r'(pythiaPtr|pythia) *(\.|->) *word *\(\s*"(.*?)" *\)', wsub3, s)
        s = re.sub(r'(pythiaPtr|pythia) *(\.|->) *fvec *\(\s*"(.*?)" *\)', flsub3, s)
        s = re.sub(r'(pythiaPtr|pythia) *(\.|->) *mvec *\(\s*"(.*?)" *\)', mlsub3, s)
        s = re.sub(r'(pythiaPtr|pythia) *(\.|->) *pvec *\(\s*"(.*?)" *\)', plsub3, s)

        if s != sorig:
          f = open(subdir + "/" + file,"w")
          f.write(s)
          f.close()

        # m =  re.finditer(r'(isFlag|addFlag|flag|flagDefault|resetFlag)\s*\(\s*"(.+?:.+?)"', s)
        # for x in m: Flag_dict[str(x.group(3)).lower()] = x.group(3)
        # m =  re.finditer(r'(isMode|addMode|mode|modeDefault|resetMode|forceMode)\s*\(\s*"(.+?:.+?)"', s)
        # for x in m: Mode_dict[str(x.group(3)).lower()] = x.group(3)
        # m =  re.finditer(r'(isParm|addParm|parm|parmDefault|resetParm|forceParm)\s*\(\s*"(.+?:.+?)"', s)
        # for x in m: Param_dict[str(x.group(3)).lower()] = x.group(3)
        # m =  re.finditer(r'(isWord|addWord|word|wordDefault|resetWord)\s*\(\s*"(.+?:.+?)"', s)
        # for x in m: Word_dict[str(x.group(3)).lower()] = x.group(3)
        # m =  re.finditer(r'(isFVec|addFVec|fvec|fvecDefault|resetFVec)\s*\(\s*"(.+?:.+?)"', s)
        # for x in m: FlagList_dict[str(x.group(3)).lower()] = x.group(3)
        # m =  re.finditer(r'(isMVec|addMVec|mvec|mvecDefault|resetMVec|forceMVec)\s*\(\s*"(.+?:.+?)"', s)
        # for x in m: ModeList_dict[str(x.group(3)).lower()] = x.group(3)
        # m =  re.finditer(r'(isPVec|addPVec|pvec|pvecDefault|resetPVec|forcePVec)\s*\(\s*"(.+?:.+?)"', s)
        # for x in m: ParamList_dict[str(x.group(3)).lower()] = x.group(3)

for x in Flag: Flag_dict[x.lower()] = x
for x in Mode: Mode_dict[x.lower()] = x
for x in Param: Param_dict[x.lower()] = x
for x in Word: Word_dict[x.lower()] = x
for x in FlagList: FlagList_dict[x.lower()] = x
for x in ModeList: ModeList_dict[x.lower()] = x
for x in ParamList: ParamList_dict[x.lower()] = x


def printDict(d, name):

  tmp = list(d.values())
  tmp.sort(key=str.casefold)

  # # print enum list
  # print("enum class", name)
  # print("{")
  # for x in tmp: print(" ", format(x) + ",")
  # print("  END,\n};\n")

  # print string -> enum maps
  print("const map<string,",name+">", name+"Map = ")
  print("{")
  for x in tmp: print("  {", '"' + x + '",', name + "::" + format(x), "},")
  print("};\n")

# printDict(Flag_dict, "Flag")
# printDict(Mode_dict, "Mode")
# printDict(Param_dict, "Param")
# printDict(Word_dict, "Word")
# printDict(FlagList_dict, "FlagList")
# printDict(ModeList_dict, "ModeList")
# printDict(ParamList_dict, "ParamList")
